
export const ZF_NAME = "zhangfei"
export const CC_NAME = "caocao"
export const MC_NAME = "machao"
export const ZY_NAME = "zhaoyun"
export const GY_NAME = "guoyu"
export const HZ_NAME = "huangzhong"
export const B1_NAME = "bing1"
export const B2_NAME = "bing2"
export const B3_NAME = "bing3"
export const B4_NAME = "bing4"

export const UP_NAME = "up"
export const LEFT_NAME = "left"
export const DOWN_NAME = "down"
export const RIGHT_NAME = "right"